require('jquery');
require('popper.js');
require('./bootstrap');
require('pace');
require('perfect-scrollbar');
require('@coreui/coreui');
require('chart.js');
require('bootstrap-select');
require('sweetalert2');
